version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  apisip:
    depends_on:
      - db
    image: node-apisip
    ports:
      - 5000:5000
  websip:
    restart: always
    image: node-websip
    ports:
      - 2000:2000
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports: 
      - "8080:80"
    environment: 
      PMA_HOST: db:3306
      MYSQL_ROOT_PASSWORD: root
volumes:
  db: